@startuml
'https://plantuml.com/sequence-diagram

abstract class Vehicle{
+info: JSON
+build(): object
+displayInfo() : void
}

class Car{

+build() 
}

class Truck{
+static createWithTransportContainer()
+build();
}


Car --> Vehicle
Truck --> Vehicle



@enduml